apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-cicd-app
  namespace: production

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: production-cicd-app

  template:
    metadata:
      labels:
        app: production-cicd-app

    spec:
      containers:
        - name: production-cicd-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 3000
